// Actual modal renderer/lifecycle/handlers with fake DOM + capture storage.
// No network requests; validates frozen reads, deliberate actions, copy consistency and hot path.
// Usage: node ring_modal_freeze.test.cjs <extension.js>
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(process.argv[2],'utf8');
function extract(name){const m=source.match(new RegExp('^  function '+name+'\\([^\\n]*\\) \\{[\\s\\S]*?^  \\}','m'));if(!m)throw Error(name);return m[0];}
let passed=0,failed=0;function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.stack);}}
const SID='9b771fe5',KEY=SID+'::model::host::direct';
function capture(id,model='model',sid=SID){return {id,ts:1000,ts_local:'test time',url:'https://host/v1/chat/completions',protocol:'openai-chat-completions',session_id:sid,_identity:{key:sid+'::'+model+'::host::direct',model,host:'host',proxy:false},body:{model,messages:[{role:'user',content:'body '+id}],tools:[]},response_status:200,response_ok:true,response_body:{text:'response '+id},response_usage:{cost:0.01},_think_req:{protocol:'openai-chat-completions'},_think_obs:null};}
function harness(initial=[capture('one')]){
 let live=initial,costs={[KEY]:{_total:2,_cache_hits:3,_cache_misses:1}},reads=0,costReads=0,discovery=0,summaryCalls=0,hashCalls=0,domWrites=0,clock=100000;const copies=[],reports=[];let ctx;
 const elems={};class Element{constructor(tag){this.tagName=tag.toUpperCase();this.style={};this.children=[];this.handlers={};this.scrollTop=0;this.dataset={};this.isConnected=true;}set innerHTML(v){this.html=v;if(this.id==='tm-payload-capture-modal-body')domWrites++;}get innerHTML(){return this.html||'';}appendChild(e){e.parentNode=this;this.children.push(e);if(e.id)elems[e.id]=e;return e;}removeChild(e){this.children=this.children.filter(x=>x!==e);e.parentNode=null;}addEventListener(k,fn){(this.handlers[k]||(this.handlers[k]=[])).push(fn);}removeEventListener(k,fn){this.handlers[k]=(this.handlers[k]||[]).filter(x=>x!==fn);}querySelector(q){if(q==='[data-role="capture-snapshot-status"]')return label;return null;}}
 const label={textContent:''};const document={body:new Element('body'),head:new Element('head'),createElement:t=>new Element(t),getElementById:id=>elems[id]||null};const listeners={};const win={addEventListener(k,f){(listeners[k]||(listeners[k]=[])).push(f);},removeEventListener(k,f){listeners[k]=(listeners[k]||[]).filter(x=>x!==f);}};
 const c={console,Date:class extends Date{static now(){return clock;}},document,window:win,payloadCaptureModalEl:null,payloadCaptureModalInnerEl:null,tmPayloadCaptureSnapshot:null,tmPayloadCaptureModalEscapeKeydownSnapshotter:null,tmPayloadCaptureModalEscapeHandler:null,tmEscapeGuardSnapshot:null,tmPayloadCaptureSuppressEscapeUntil:0,tmPromptActive:false,
 tmModalFilterListboxOpen:false,tmModalFilterIdentity:null,tmModalSortMode:'chronological',tmModalTimeFilter:'all',
 TM_PAYLOAD_CAPTURE_RING_KEY:'ring',TM_PAYLOAD_CAPTURE_ENABLED_KEY:'enabled',TM_PAYLOAD_CAPTURE_MAX_ENTRIES:500,TM_PAYLOAD_CAPTURE_MAX_OUTBOUND_CHARS:1000,TM_PAYLOAD_CAPTURE_MAX_RESPONSE_CHARS:1000,TM_PAYLOAD_CAPTURE_MAX_RICH_ENTRIES:100,
 tmReadCaptureRing(){reads++;return JSON.parse(JSON.stringify(live));},tmGetSessionCosts(){costReads++;return JSON.parse(JSON.stringify(costs));},getCaptureById:id=>JSON.parse(JSON.stringify(live.find(c=>c.id===id)||null)),tmDiscoverAndMergeProviderRatings(){discovery++;},tmDiscoverAndMergeProviderCosts(){discovery++;},
 tmBuildSessionCostKey:(s,m,h,p)=>[s,m,h,p?'proxy':'direct'].join('::'),tmCaptureModel:cap=>cap._identity?.model||cap.body?.model||'',tmComputeSystemToolsPrefixHash:b=>{hashCalls++;return 'hash-'+(b?.messages?.[0]?.content||'empty');},
 tmCapIdentityKey:cap=>cap._identity.key,tmCapIdentityLabel:cap=>({label:cap.session_id,model:cap._identity.model,host:'host',sid:cap.session_id,isProxy:false}),tmModelEndpointColor:()=>'#abcdef',tmExtractEndpointHost:()=>'host',tmIsProxyCapture:()=>false,
 tmGetHideRetries:()=>false,tmSetHideRetries(){},tmIsRetryRow:()=>false,tmIsDeadProxyProbeRow:()=>false,tmApplyTimeFilter:items=>items,tmAgentManagementEnabled:()=>false,tmBuildCaptureStatusBanner:()=>'<div>Capture enabled</div>',tmGetSolReasoningEffort:()=>'high',tmGetModelProviderMap:()=>({}),tmGetProviderEntries:()=>[],tmShouldBlockOpenRouterGemini:()=>true,tmCaptureEnabled:()=>true,
 tmSortModalItems:items=>{if(ctx.tmModalSortMode==='turn-cost')items.reverse();return items;},tmBuildTimelineSeparator:()=>'',tmIsMultiProviderModel:()=>false,tmThinkControlSupportedForIdentity:()=>false,tmIsSignificantCacheHit:()=>true,tmExtractCostVal:(au,u)=>u?.cost||0,tmRenderRepairBlocks:()=>'',tmRenderCacheReport:()=>'cache',tmRenderCtxDial:()=>'',tmRenderThinkBadge:()=>'',tmGetSessionName:()=>'',tmBuildCaptureSummary:cap=>{summaryCalls++;return {id:cap.id,model:cap.body.model,body:cap.body};},
 tmThinkClassifyReq:()=>({glyphs:[]}),tmThinkClassifyObs:()=>({glyphs:[]}),tmThinkCompactReq:()=>'',tmThinkCompactObs:()=>'',tmThinkInterpret:()=>[],tmAnyChildModalOpen:()=>false,
 copyTextToClipboard:(txt,label)=>copies.push({txt,label}),tmShowJsonViewerModal:(txt,label)=>reports.push({txt,label}),renderGpt51UsageWidget(){},tmSetSessionName(){},prompt:()=>null,setTimeout:()=>1,localStorage:{setItem(){}}
 };
 ctx=vm.createContext(c);
 const funcs=['escapeHtml','tmCreatePayloadCaptureSnapshot','tmPreparePayloadCaptureRender','tmGetPayloadCaptureViewRecord','tmPayloadCaptureViewCost','tmPayloadCaptureRowMetadata','tmCollectRingModels','ensurePayloadCaptureModal','renderPayloadCaptureModal','tmRenderPayloadCaptureModalSnapshot','openPayloadCaptureModal','closePayloadCaptureModal','copyPayloadCapturePart','tmShowThinkReport'];
 vm.runInContext(funcs.map(extract).join('\n'),ctx);
 function action(act,type='click',extra={}){const t={dataset:{action:act,...extra.dataset},value:extra.value,closest(selector){return selector.includes('[data-action="'+act+'"]')?this:null;}};const ev={target:t,stopPropagation(){},preventDefault(){}};for(const handler of ctx.payloadCaptureModalEl.handlers[type]||[])handler(ev);}
 return {c:ctx,document,win,label,copies,reports,action,live:()=>live,setLive:x=>live=x,setCosts:x=>costs=x,advance:x=>clock+=x,counts:()=>({reads,costReads,discovery,summaryCalls,hashCalls,domWrites}),listeners};
}
test('opening creates one snapshot; 1000 background renders do no reads/writes',()=>{const h=harness();h.c.openPayloadCaptureModal();const before=h.counts(),snap=h.c.tmPayloadCaptureSnapshot;for(let i=0;i<1000;i++)assert.equal(h.c.renderPayloadCaptureModal(),false);assert.deepEqual(h.counts(),before);assert.equal(h.c.tmPayloadCaptureSnapshot,snap);assert.match(h.label.textContent,/Frozen at/);});
test('background capture arrival/completion does not alter open rows or snapshot',()=>{const h=harness();h.c.openPayloadCaptureModal();const html=h.c.payloadCaptureModalInnerEl.innerHTML;h.live()[0].response_body.text='newer response';h.live().push(capture('two'));h.c.renderPayloadCaptureModal();assert.equal(h.c.payloadCaptureModalInnerEl.innerHTML,html);assert.equal(h.c.tmPayloadCaptureSnapshot.ring.length,1);assert.equal(h.c.tmPayloadCaptureSnapshot.byId.one.response_body.text,'response one');});
test('Refresh explicitly acquires latest data and resets to top',()=>{const h=harness();h.c.openPayloadCaptureModal();h.c.payloadCaptureModalInnerEl.scrollTop=400;h.live().push(capture('two'));h.action('refresh-payload-capture-modal');assert.equal(h.c.tmPayloadCaptureSnapshot.ring.length,2);assert.equal(h.c.payloadCaptureModalInnerEl.scrollTop,0);assert.match(h.c.payloadCaptureModalInnerEl.innerHTML,/data-capture-id="two"/);});
test('filter/listbox/sort/time/noise actions use the same snapshot without reacquiring',()=>{const h=harness([capture('one'),capture('two','other','different')]);h.c.openPayloadCaptureModal();const snap=h.c.tmPayloadCaptureSnapshot,before=h.counts();h.c.payloadCaptureModalInnerEl.scrollTop=50;h.action('toggle-modal-filter-listbox');assert.equal(h.c.tmModalFilterListboxOpen,true);h.action('set-modal-filter-listbox','click',{dataset:{identityKey:KEY}});assert.equal(h.c.tmModalFilterIdentity,KEY);assert.doesNotMatch(h.c.payloadCaptureModalInnerEl.innerHTML,/data-capture-id="two"/);h.action('set-modal-sort','click',{dataset:{sortMode:'turn-cost'}});h.action('set-modal-time-filter','change',{value:'12h'});h.action('toggle-hide-retries');assert.equal(h.c.tmPayloadCaptureSnapshot,snap);assert.equal(h.counts().reads,before.reads);assert.equal(h.counts().discovery,before.discovery);assert.equal(h.counts().costReads,before.costReads);assert.equal(h.c.payloadCaptureModalInnerEl.scrollTop,50);});
test('row-copy remains the displayed bytes after eviction from the live ring',()=>{const h=harness();h.c.openPayloadCaptureModal();h.setLive([capture('two')]);h.c.copyPayloadCapturePart('one','in_payload');assert.equal(JSON.parse(h.copies.at(-1).txt).body.text,'response one');h.c.copyPayloadCapturePart('one','summary');assert.equal(JSON.parse(h.copies.at(-1).txt).id,'one');assert.equal(h.counts().summaryCalls,1);});
test('an ID absent from an open snapshot is not silently read from live storage',()=>{const h=harness();h.c.openPayloadCaptureModal();h.live().push(capture('new'));assert.equal(h.c.tmGetPayloadCaptureViewRecord('new'),null);h.c.copyPayloadCapturePart('new','summary');assert.equal(h.copies.length,0);});
test('thinking-report click uses displayed snapshot, not subsequently changed evidence',()=>{const h=harness();h.live()[0]._think_req={summary:'before'};h.c.openPayloadCaptureModal();h.live()[0]._think_req.summary='after';h.action('think-report','click',{dataset:{captureId:'one'}});assert.equal(JSON.parse(h.reports.at(-1).txt).requested.summary,'before');});
test('close releases snapshot; hidden notifications do no work; reopen is fresh',()=>{const h=harness();h.c.openPayloadCaptureModal();h.c.closePayloadCaptureModal();assert.equal(h.c.tmPayloadCaptureSnapshot,null);const before=h.counts();h.live().push(capture('two'));h.c.renderPayloadCaptureModal();h.c.renderPayloadCaptureModal('view');assert.deepEqual(h.counts(),before);h.c.openPayloadCaptureModal();assert.equal(h.c.tmPayloadCaptureSnapshot.ring.length,2);});
test('Escape first closes listbox, second closes modal; no accumulating listeners',()=>{const h=harness();h.c.openPayloadCaptureModal();h.c.tmModalFilterListboxOpen=true;const ev={key:'Escape',code:'Escape',stopPropagation(){},preventDefault(){}};for(const f of [...h.listeners.keydown])f(ev);for(const f of [...h.listeners.keyup])f(ev);assert.equal(h.c.tmModalFilterListboxOpen,false);assert.equal(h.c.payloadCaptureModalEl.style.display,'block');for(const f of [...h.listeners.keydown])f(ev);for(const f of [...h.listeners.keyup])f(ev);assert.equal(h.c.payloadCaptureModalEl.style.display,'none');assert.equal(h.listeners.keyup.length,0);h.c.openPayloadCaptureModal();assert.equal(h.listeners.keydown.length,1);assert.equal(h.listeners.keyup.length,1);});
test('500 rows do not build full summaries; redisplay reuses prefix hash metadata',()=>{const h=harness(Array.from({length:500},(_,i)=>capture('capture'+i)));h.c.openPayloadCaptureModal();assert.equal(h.counts().summaryCalls,0);assert.equal(h.counts().hashCalls,500);const before=h.counts();h.c.renderPayloadCaptureModal('view');assert.equal(h.counts().hashCalls,before.hashCalls);assert.equal(h.counts().reads,before.reads);assert.equal(h.counts().costReads,before.costReads);assert.match(h.c.payloadCaptureModalInnerEl.innerHTML,/#500/);});
test('cost totals stay at snapshot values until Refresh',()=>{const h=harness();h.c.openPayloadCaptureModal();assert.match(h.c.payloadCaptureModalInnerEl.innerHTML,/\$2\.00/);h.setCosts({[KEY]:{_total:999}});h.c.renderPayloadCaptureModal('view');assert.doesNotMatch(h.c.payloadCaptureModalInnerEl.innerHTML,/\$999\.00/);h.action('refresh-payload-capture-modal');assert.match(h.c.payloadCaptureModalInnerEl.innerHTML,/\$999\.00/);});
test('empty snapshot remains frozen until Refresh',()=>{const h=harness([]);h.c.openPayloadCaptureModal();assert.match(h.c.payloadCaptureModalInnerEl.innerHTML,/No captured payloads in this snapshot/);h.live().push(capture('one'));h.c.renderPayloadCaptureModal();assert.equal(h.c.tmPayloadCaptureSnapshot.ring.length,0);h.action('refresh-payload-capture-modal');assert.equal(h.c.tmPayloadCaptureSnapshot.ring.length,1);});
test('explicitly missing snapshot report never substitutes live data',()=>{const h=harness();h.c.openPayloadCaptureModal();h.c.tmShowThinkReport('one',null);assert.equal(h.reports.length,0);h.c.tmShowThinkReport('one');assert.equal(h.reports.length,1);});
test('explicit setting callbacks still request a view render',()=>{for(const n of ['tmHandleThinkControlChange','tmHandleProviderRoutingChange','tmCtxDialPromptSet']){const code=extract(n);assert.match(code,/renderPayloadCaptureModal\('view'\)/,n);assert.doesNotMatch(code,/renderPayloadCaptureModal\(\)/,n);}});
console.log(`\n${passed} passed; ${failed} failed`);process.exitCode=failed?1:0;
