// Regression tests for dashboard delta updates and bounded KA message-pattern history.
// Runs production functions in a fake DOM with a virtual clock; no network or browser needed.
// Usage: node sessions_delta_history.test.cjs <extension.js>
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(process.argv[2],'utf8');
function extract(name){const m=source.match(new RegExp('^  function '+name+'\\([^\\n]*\\) \\{[\\s\\S]*?^  \\}','m'));if(!m)throw Error(name);return m[0];}
let pass=0,fail=0;
function test(name,run){try{run();pass++;console.log('PASS '+name);}catch(e){fail++;console.error('FAIL '+name+': '+e.message);}}
const escapeHtml=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function base(){let time=1000000,writes=0;const data={};class Clock extends Date{constructor(...args){super(...(args.length?args:[time]));}static now(){return time;}}
 const x={Date:Clock,console:{warn(...v){throw Error(v.map(String).join(' '));},log(){}},escapeHtml,TM_KA_MESSAGES_KEY:'tm_keepalive_messages_v1',tmKeepAliveStatus:{},tmFmtDuration:ms=>Math.floor(ms/1000)+'s',tmThinkFmtK:n=>String(n),localStorage:{getItem:k=>data[k]||null,setItem(k,v){data[k]=String(v);writes++;}}};
 const c=vm.createContext(x);return {c,data,advance:n=>{time+=n;},now:()=>time,writes:()=>writes};}
function history(){const h=base();vm.runInContext(['tmKeepAliveNormSid','tmKeepAliveMessageTemplate','tmReadKeepAliveMessages','tmKeepAliveRememberMessage','tmKeepAliveSetStatus','tmKeepAliveSummaryText','tmShowKeepAliveMessages'].map(extract).join('\n'),h.c);h.rows=sid=>h.c.tmReadKeepAliveMessages()[sid].rows;return h;}
const key='tm-9b771fe5::model::host::direct';
test('countdown units and values normalize to one template',()=>{const h=history();assert.equal(h.c.tmKeepAliveMessageTemplate('next ping in 2m'),h.c.tmKeepAliveMessageTemplate('next ping in 45s'));});
test('dollars, counts, times and token amounts become placeholders',()=>{const h=history();const a=h.c.tmKeepAliveMessageTemplate('pings 2 · $0.260 · 12:34 ✓248K/0'),b=h.c.tmKeepAliveMessageTemplate('pings 19 · $12.521 · 02:59 ✓501K/0');assert.equal(a,b);assert.equal(a,'pings □ · $□ · □ ✓□/□');});
test('1000 timer ticks cause one occurrence and one storage write',()=>{const h=history();for(let i=1000;i>0;i--){h.c.tmKeepAliveSetStatus(key,{text:'next ping in '+i+'s',tone:'muted'});h.advance(1000);}assert.equal(h.rows('9b771fe5')[0].count,1);assert.equal(h.writes(),1);assert.equal(h.rows('9b771fe5')[0].last_at,1000000);});
test('a recurring failure is counted after leaving and re-entering it',()=>{const h=history();h.c.tmKeepAliveSetStatus(key,{text:'ping failed HTTP 429; retry in 60s'});h.advance(1000);h.c.tmKeepAliveSetStatus(key,{text:'ping sent'});h.advance(1000);h.c.tmKeepAliveSetStatus(key,{text:'ping failed HTTP 503; retry in 30s'});assert.equal(h.rows('9b771fe5').find(r=>r.template.startsWith('ping failed')).count,2);});
test('separate real ping results count even when only their numbers differ',()=>{const h=history();h.c.tmKeepAliveRememberMessage(key,'pings 1 · $0.13','summary:a');h.advance(1000);h.c.tmKeepAliveRememberMessage(key,'pings 2 · $0.26','summary:b');h.c.tmKeepAliveRememberMessage(key,'pings 2 · $0.26','summary:b');assert.equal(h.rows('9b771fe5')[0].count,2);assert.equal(h.rows('9b771fe5')[0].last_at,1001000);});
test('history is session scoped and raw/tm- aliases share it',()=>{const h=history();h.c.tmKeepAliveRememberMessage(key,'pings 1','a');h.c.tmKeepAliveRememberMessage(key.replace('tm-',''),'pings 2','b');h.c.tmKeepAliveRememberMessage('another::m::h::direct','pings 3','c');assert.equal(h.rows('9b771fe5')[0].count,2);assert.equal(h.rows('another')[0].count,1);});
test('deduplication survives reload',()=>{const h=history();h.c.tmKeepAliveSetStatus(key,{text:'next ping in 50m'});const j=history();Object.assign(j.data,h.data);j.c.tmKeepAliveSetStatus(key,{text:'next ping in 40m'});assert.equal(j.rows('9b771fe5')[0].count,1);assert.equal(j.writes(),0);});
test('16 pattern per-session bound is enforced',()=>{const h=history();for(let i=0;i<40;i++){h.advance(1);h.c.tmKeepAliveRememberMessage(key,'pattern '+String.fromCharCode(65+i),'event'+i);}assert.equal(h.rows('9b771fe5').length,16);});
test('40-session bound and 64Ki-character budget are enforced',()=>{const h=history();for(let i=0;i<55;i++){h.advance(1);for(let j=0;j<16;j++)h.c.tmKeepAliveRememberMessage('sid'+i+'::m::h::direct',String.fromCharCode(65+j)+' '+'long'.repeat(95),'event'+j);}const raw=h.data.tm_keepalive_messages_v1;assert.ok(raw.length<=65536,raw.length);assert.ok(Object.keys(JSON.parse(raw)).length<=40);assert.ok(h.c.tmReadKeepAliveMessages().sid54);});
test('history report is escaped, colored, copyable and a read-only snapshot',()=>{const h=history();h.c.tmKeepAliveRememberMessage(key,'failure <img src=x onerror=oops> 123','event');h.advance(60000);let report;h.c.tmShowJsonViewerModal=(...args)=>{report=args;};const before=h.writes();h.c.tmShowKeepAliveMessages(key);assert.equal(h.writes(),before);assert.match(report[2].contentHtml,/&lt;img/);assert.doesNotMatch(report[2].contentHtml,/<img/);assert.match(report[2].contentHtml,/color:#7ec8e3/);assert.match(report[2].copyText,/\(1\).*last seen 60s ago/);});

function dashboard(){const h=base();const c=h.c;let ringReads=0,costReads=0,kaReads=0,full=0,domWrites=0;const keys=Array.from({length:40},(_,i)=>'s'+i+'::m::h::direct');const ring=keys.map((k,i)=>({id:'cap'+i,_identity:{key:k},_rt_ms:1000,_ctx_snapshot:{total:100},_think_req:{}}));const costs=Object.fromEntries(keys.map(k=>[k,{_rt_total_ms:1000}]));const states={};
 function zone(key){return {key,writes:0,getAttribute(){return key;},set innerHTML(v){this.html=v;this.writes++;domWrites++;},get innerHTML(){return this.html;}};}
 const zones=keys.map(zone),spins=keys.map(zone),kas=keys.map(zone);let selected=null;
 const el={style:{display:'flex'},contains:n=>!!n&&n.inside===true,querySelectorAll:s=>s==='[data-live-key]'?zones:s==='[data-spin-key]'?spins:s==='[data-ka-key]'?kas:[]};
 const content={scrollTop:275,set innerHTML(v){full++;this.html=v;},get innerHTML(){return this.html;}};
 Object.assign(c,{tmSessionCtxHoverEl:el,tmSessionCtxHoverContentEl:content,tmSessionCtxHoverPinned:true,tmSessionCtxHoverLastFullAt:h.now(),tmSessionCtxHoverLastScrollAt:0,tmSessionCtxHoverDrag:null,tmPromptActive:false,
 tmSessionCtxHoverIdentities:Object.fromEntries(keys.map((k,i)=>[k,{sid:'s'+i,model:'m',host:'h',isProxy:false}])),tmInFlightByIdentity:{},tmInFlightTurn:null,tmToolStateUnresolvedLogged:{},
 tmReadCaptureRing(){ringReads++;return ring;},tmGetSessionCosts(){costReads++;return costs;},tmGetKeepAliveStore(){kaReads++;return {};},tmGetKeepAliveEntry(){throw Error('must use shared KA store');},tmBuildSessionCostKey:(s,m,host,p)=>[s,m,host,p?'proxy':'direct'].join('::'),
 tmCapIdentityKey:cap=>cap._identity.key,tmAgentManagementEnabled:()=>true,tmAgentManagementDisplayState:s=>states[s],tmAgentManagementBadge:()=>'<span>tool</span>',tmAgentManagementClearBadge:()=>'<span>clear</span>',
 getCaptureById(){throw Error('no per-row ring reads');},tmLatestRoundTripEntryForIdentity(){throw Error('no per-row ring reads');},
 document:{activeElement:null},window:{getSelection:()=>selected},
 tmBuildSessionCtxHoverHtml(){c.tmSessionCtxHoverLastFullAt=h.now();return 'full build';}
 });
 vm.runInContext(['tmToolStateIdentityKey','tmSessionCtxIsBusy','tmSessionCtxLiveHtml','tmBuildSessionCtxLiveFrame','tmSessionCtxPatchHtml','tmSessionCtxInteractionBusy','tmRefreshSessionCtxKeepAlive','tmSessionCtxHoverTick','tmKeepAliveRowHtml','tmKeepAliveSummaryText','tmKeepAliveRefreshUI'].map(extract).join('\n'),c);
 return {...h,keys,ring,costs,states,zones,spins,kas,el,content,setSelection:s=>{selected=s;},counts:()=>({ringReads,costReads,kaReads,full,domWrites})};}
test('40 idle rows use one ring/cost/KA read per tick; next tick writes nothing',()=>{const h=dashboard();h.c.tmSessionCtxHoverTick();const a=h.counts();assert.equal(a.ringReads,1);assert.equal(a.costReads,1);assert.equal(a.kaReads,1);h.advance(1000);h.c.tmSessionCtxHoverTick();const b=h.counts();assert.equal(b.domWrites,a.domWrites);assert.equal(b.ringReads,2);assert.equal(b.full,0);});
test('only the active timer changes; its spinner DOM is not recreated each second',()=>{const h=dashboard();h.c.tmSessionCtxHoverTick();h.c.tmInFlightByIdentity[h.keys[0]]={ts:h.now()-1000};h.advance(1000);h.c.tmSessionCtxHoverTick();const first=h.counts(),spins=h.spins[0].writes;h.advance(1000);h.c.tmSessionCtxHoverTick();assert.equal(h.counts().domWrites-first.domWrites,1);assert.equal(h.spins[0].writes,spins);assert.equal(h.zones[1].writes,1);});
test('tool activity resolves to its own identity using the shared capture index',()=>{const h=dashboard();h.states.s0={pendingToolCall:true,responseFinishedAt:h.now()-1000,captureId:'cap0'};h.c.tmSessionCtxHoverTick();assert.match(h.zones[0].html,/tool/);assert.doesNotMatch(h.zones[1].html,/tool/);assert.match(h.spins[0].html,/tm-hc-spin/);assert.equal(h.spins[1].html,'');assert.equal(h.counts().ringReads,1);});
test('full rebuild is 30 seconds, not 3, and preserves scroll',()=>{const h=dashboard();for(let i=0;i<29;i++){h.advance(1000);h.c.tmSessionCtxHoverTick();}assert.equal(h.counts().full,0);h.advance(1000);h.c.tmSessionCtxHoverTick();assert.equal(h.counts().full,1);assert.equal(h.content.scrollTop,275);});
test('active scrolling postpones the full rebuild until scrolling stops',()=>{const h=dashboard();h.advance(30000);h.c.tmSessionCtxHoverLastScrollAt=h.now();h.c.tmSessionCtxHoverTick();assert.equal(h.counts().full,0);assert.equal(h.counts().ringReads,0);h.advance(400);h.c.tmSessionCtxHoverTick();assert.equal(h.counts().full,1);});
test('dropdown, text selection, drag and child modal prevent destructive refreshes',()=>{for(const type of ['dropdown','selection','drag','modal']){const h=dashboard();h.advance(30000);if(type==='dropdown')h.c.document.activeElement={tagName:'SELECT',inside:true};if(type==='selection')h.setSelection({isCollapsed:false,anchorNode:{inside:true}});if(type==='drag')h.c.tmSessionCtxHoverDrag={};if(type==='modal')h.c.tmPromptActive=true;h.c.tmSessionCtxHoverTick();assert.equal(h.counts().full,0,type);assert.equal(h.counts().domWrites,0,type);}});
test('hidden card does no reads or writes; unpinned card keeps delta-only behavior',()=>{const h=dashboard();h.el.style.display='none';h.advance(31000);h.c.tmSessionCtxHoverTick();assert.equal(h.counts().ringReads,0);h.el.style.display='flex';h.c.tmSessionCtxHoverPinned=false;h.c.tmSessionCtxHoverTick();assert.equal(h.counts().full,0);assert.equal(h.counts().ringReads,1);});
test('KA UI refresh patches only KA zones, never the entire dashboard',()=>{const h=dashboard();h.c.tmSessionCtxHoverTick();const before=h.counts();h.c.tmKeepAliveStatus[h.keys[0]]={text:'changed',tone:'warn'};h.c.tmKeepAliveRefreshUI();assert.equal(h.counts().full,before.full);assert.equal(h.counts().ringReads,before.ringReads);assert.equal(h.zones[0].writes,1);});
test('each KA row has a history button without reading or recording history in render',()=>{const h=dashboard();h.c.tmSessionCtxHoverTick();assert.match(h.kas[0].html,/data-action="ka-messages"/);assert.equal(h.writes(),0);});
console.log(`\n${pass} passed; ${fail} failed`);process.exitCode=fail?1:0;
